"""initial schema

Revision ID: 28353c59ee4c
Revises: 
Create Date: 2026-10-03 12:20:20.188395
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28353c59ee4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Native PostgreSQL enum types (see docs/DATABASE.md). Created/dropped
# explicitly with checkfirst so `downgrade base && upgrade head` is fully
# reversible — autogenerated drop_table alone would leave orphan types.
ENUM_TYPES = [
    postgresql.ENUM("admin", "sales", name="user_role"),
    postgresql.ENUM("manual_import", "osm", "google_places", "manual", name="source_type"),
    postgresql.ENUM(
        "glovo", "uber_eats", "just_eat", "deliveroo", "own_delivery", "other",
        name="delivery_platform",
    ),
    postgresql.ENUM("website_link", "manual", "api", name="detection_method"),
    postgresql.ENUM("phone", "email", "whatsapp", "website", "address", name="contact_type"),
    postgresql.ENUM("call", "whatsapp", "email", "meeting", "other", name="interaction_channel"),
    postgresql.ENUM(
        "no_answer", "busy", "callback_requested", "interested", "not_interested",
        "meeting_scheduled", "wrong_number", "out_of_area", "duplicate_reported",
        name="interaction_result",
    ),
    postgresql.ENUM("pending", "completed", "postponed", "cancelled", name="follow_up_status"),
    postgresql.ENUM(
        "new", "qualified", "contacted", "no_response", "follow_up", "interested",
        "meeting", "customer", "not_interested", "wrong_number", "out_of_area",
        "duplicate", name="lead_status",
    ),
    postgresql.ENUM("low", "medium", "high", name="lead_priority"),
    postgresql.ENUM(
        "briefing", "call_script", "commercial_message", "follow_up_message",
        name="generation_type",
    ),
]


def upgrade() -> None:
    for enum_type in ENUM_TYPES:
        enum_type.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('phone_source', postgresql.ENUM('manual_import', 'osm', 'google_places', 'manual', name='source_type', create_type=False), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('email_source', postgresql.ENUM('manual_import', 'osm', 'google_places', 'manual', name='source_type', create_type=False), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('website_source', postgresql.ENUM('manual_import', 'osm', 'google_places', 'manual', name='source_type', create_type=False), nullable=True),
    sa.Column('website_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('possible_duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['possible_duplicate_of_id'], ['restaurants.id'], name=op.f('fk_restaurants_possible_duplicate_of_id_restaurants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurants'))
    )
    op.create_index(op.f('ix_restaurants_city'), 'restaurants', ['city'], unique=False)
    op.create_index('ix_restaurants_city_category', 'restaurants', ['city', 'category'], unique=False)
    op.create_index(op.f('ix_restaurants_normalized_name'), 'restaurants', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_restaurants_phone'), 'restaurants', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'sales', name='user_role', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('ai_generations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('generation_type', postgresql.ENUM('briefing', 'call_script', 'commercial_message', 'follow_up_message', name='generation_type', create_type=False), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ai_generations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_ai_generations_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generations'))
    )
    op.create_index('ix_ai_generations_restaurant_created_at', 'ai_generations', ['restaurant_id', 'created_at'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('contact_type', postgresql.ENUM('phone', 'email', 'whatsapp', 'website', 'address', name='contact_type', create_type=False), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', postgresql.ENUM('manual_import', 'osm', 'google_places', 'manual', name='source_type', create_type=False), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_contacts_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index('ix_contacts_restaurant_contact_type', 'contacts', ['restaurant_id', 'contact_type'], unique=False)
    op.create_table('delivery_presence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', postgresql.ENUM('glovo', 'uber_eats', 'just_eat', 'deliveroo', 'own_delivery', 'other', name='delivery_platform', create_type=False), nullable=False),
    sa.Column('detected', sa.Boolean(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('detection_method', postgresql.ENUM('website_link', 'manual', 'api', name='detection_method', create_type=False), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_delivery_presence_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_presence')),
    sa.UniqueConstraint('restaurant_id', 'platform', name=op.f('uq_delivery_presence_restaurant_id_platform'))
    )
    op.create_table('follow_ups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel', postgresql.ENUM('call', 'whatsapp', 'email', 'meeting', 'other', name='interaction_channel', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'postponed', 'cancelled', name='follow_up_status', create_type=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_follow_ups_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_follow_ups_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_ups'))
    )
    op.create_index('ix_follow_ups_status_scheduled_at', 'follow_ups', ['status', 'scheduled_at'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('channel', postgresql.ENUM('call', 'whatsapp', 'email', 'meeting', 'other', name='interaction_channel', create_type=False), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', postgresql.ENUM('no_answer', 'busy', 'callback_requested', 'interested', 'not_interested', 'meeting_scheduled', 'wrong_number', 'out_of_area', 'duplicate_reported', name='interaction_result', create_type=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_interactions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_interactions_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions'))
    )
    op.create_index('ix_interactions_restaurant_occurred_at', 'interactions', ['restaurant_id', 'occurred_at'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('score_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.ENUM('new', 'qualified', 'contacted', 'no_response', 'follow_up', 'interested', 'meeting', 'customer', 'not_interested', 'wrong_number', 'out_of_area', 'duplicate', name='lead_status', create_type=False), nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', name='lead_priority', create_type=False), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name=op.f('ck_leads_score_range')),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_leads_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_leads_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('restaurant_id', name=op.f('uq_leads_restaurant_id'))
    )
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_index('ix_leads_score', 'leads', [sa.literal_column('score DESC')], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index('ix_leads_status_updated_at', 'leads', ['status', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('restaurant_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('source', postgresql.ENUM('manual_import', 'osm', 'google_places', 'manual', name='source_type', create_type=False), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_sources_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurant_sources')),
    sa.UniqueConstraint('restaurant_id', 'source', 'external_id', name=op.f('uq_restaurant_sources_restaurant_id_source_external_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_restaurant_sources_source_external_id', 'restaurant_sources', ['source', 'external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_restaurant_sources_source_external_id', table_name='restaurant_sources')
    op.drop_table('restaurant_sources')
    op.drop_index('ix_leads_status_updated_at', table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index('ix_leads_score', table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_interactions_restaurant_occurred_at', table_name='interactions')
    op.drop_table('interactions')
    op.drop_index('ix_follow_ups_status_scheduled_at', table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_table('delivery_presence')
    op.drop_index('ix_contacts_restaurant_contact_type', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_ai_generations_restaurant_created_at', table_name='ai_generations')
    op.drop_table('ai_generations')
    op.drop_table('users')
    op.drop_index(op.f('ix_restaurants_phone'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_normalized_name'), table_name='restaurants')
    op.drop_index('ix_restaurants_city_category', table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_city'), table_name='restaurants')
    op.drop_table('restaurants')
    for enum_type in reversed(ENUM_TYPES):
        enum_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
